#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
    CREATE USER "$AIRFLOW_DB_USER" WITH PASSWORD '$AIRFLOW_DB_PASSWORD';
    CREATE DATABASE airflow;
    GRANT ALL PRIVILEGES ON DATABASE airflow TO "$AIRFLOW_DB_USER";

    CREATE USER "$PG_USER" WITH PASSWORD '$PG_PASS';
    CREATE DATABASE lakehouse;
    GRANT ALL PRIVILEGES ON DATABASE lakehouse TO "$PG_USER";
EOSQL
